version: '2'
services:
    urho3d-test-control:
        image: adam2092/urho3d-test-control:v0.0.4
        network_mode: "host"
        privileged: true
        volumes:
        -   /tmp/.X11-unix:/tmp/.X11-unix
        environment:
        -   DISPLAY=$DISPLAY
        command: "/opt/testRemoteControl --cid=113 --freq=30"
        
    urho3d-test-listener:
        image: adam2092/urho3d-test-control:v0.0.4
        network_mode: "host"
        privileged: true
        depends_on:
        -   urho3d-test-control
        command: "/opt/Listener --cid=113"
