version: '2'
services:
    urho3d-test-control:
        image: adam2092/urho3d-test-control:v0.0.5.2
        network_mode: "host"
        privileged: true
        volumes:
        -   /tmp/.X11-unix:/tmp/.X11-unix
        -   /dev/shm:/dev/shm
        environment:
        -   DISPLAY=$DISPLAY
        -   CLUON_SHAREDMEMORY_POSIX=1
        command: "/opt/testRemoteControl --cid=113 --freq=30 --name=/vircam0"
        
#    urho3d-test-listener:
#        image: adam2092/urho3d-test-control:v0.0.5
#        network_mode: "host"
#        privileged: true
#        depends_on:
#        -   urho3d-test-control
#        command: "/opt/Listener --cid=113"
        
    urho3d-test-cameraviewer:
        image: adam2092/urho3d-test-control:v0.0.5.2
        network_mode: "host"
        privileged: true
        volumes:
        -   /tmp/.X11-unix:/tmp/.X11-unix
        -   /dev/shm:/dev/shm
        depends_on:
        -   urho3d-test-control
        environment:
        -   DISPLAY=$DISPLAY
        -   CLUON_SHAREDMEMORY_POSIX=1
        command: "/opt/CameraViewer --cid=113 --name=/vircam0"
